interface Question {
  id: number
  label: string
  options: Record<string, number | string>
  ifSkipped: number | string
  progress: number
  isMultiSelect: boolean
  isRequired: boolean
  hasTextInput: boolean
}

const questions: Question[] = [
  {
    id: 1,
    label: 'Are you sure you are pregnant',
    options: {
      'Yes, I confirmed it with a pregnancy test kit and it is positive': 5,
      'Yes, my doctor confirmed it': 5,
      No: 2,
    },
    ifSkipped: 5,
    progress: 12.5,
    isMultiSelect: false,
    isRequired: false,
    hasTextInput: false,
  },
  {
    id: 2,
    label: 'Do you have the following pregnancy symptoms?',
    options: {
      Symptom1: 'Symptom1 Issues',
      Symptom2: 'Symptom2 Issues',
      Symptom3: 'Symptom3 Issues',
      Symptom4: 'Symptom4 Issues',
      Symptom5: 'Symptom5 Issues',
    },
    ifSkipped: 5,
    progress: 16.6,
    isMultiSelect: true,
    isRequired: false,
    hasTextInput: false,
  },
  {
    id: 5,
    label: 'How do you feel?',
    options: {
      'I believe my baby deserves a chance despite my circumstances': 1,
      'I need to take care of myself first': 2,
      'The pregnancy is a great problem': 3,
      "I'm worried about what others may think of me": 4,
      "I'm worried that I lack the finance and resources to support baby": 5,
      "I feel unsure. I don't know what to do and I need help": 6,
      'I feel scared and alone. No one knows except me': 7,
      "I feel happy but in shock. I'm hopeful but need some assistance": 8,
      "I'm scared to be a Parent and I am not ready to take on the responsibility": 9,
      "I want to keep the baby and I'm ready": 10,
      "I don't want others to find out and I'm worried about what others will think of me": 11,
    },
    ifSkipped: 6,
    progress: 25,
    isMultiSelect: true,
    isRequired: false,
    hasTextInput: true,
  },
  {
    id: 6,
    label: 'What is your thought on the baby?',
    options: {
      "I believe there's a life growing inside of me": 7,
      "I believe it's just a mass of cells": 7,
      "I'm unsure and I don't know how to feel": 7,
      "It is a bundle of joy and I can't want to see him/her": 7,
      "I believe it's a miracle to have a baby": 7,
      "I don't feel anything at the moment": 7,
    },
    ifSkipped: 7,
    progress: 37.5,
    isMultiSelect: false,
    isRequired: false,
    hasTextInput: false,
  },
  {
    id: 7,
    label: 'Are you married?',
    options: {
      No: 8,
      Yes: 11,
    },
    ifSkipped: 21,
    progress: 50,
    isMultiSelect: false,
    isRequired: false,
    hasTextInput: false,
  },
  {
    id: 8,
    label: "I'm alone and...",
    options: {
      "I'm unmarried": 9,
      'My husband is in prison. What are my options?': 21,
      'I’m a divorcee/widow. What are my options?': 21,
    },
    ifSkipped: 21,
    progress: 62.5,
    isMultiSelect: false,
    isRequired: false,
    hasTextInput: false,
  },
  {
    id: 9,
    label: "I'm alone and..",
    options: {
      'My parents don’t know': 10,
      'My parents are supportive of me having the baby. What are my options?': 21,
      'My parents want me to abort the baby but I want to keep it': 10,
      'The baby’s father is married but not to me and wants me to abort':
        'submit-chat',
    },
    ifSkipped: 10,
    progress: 75,
    isMultiSelect: false,
    isRequired: false,
    hasTextInput: false,
  },
  {
    id: 10,
    label: 'I need help for someone to speak to..',
    options: {
      'My parents': 'submit-chat',
      'My school': 'submit-chat',
    },
    ifSkipped: 'submit-chat',
    progress: 87.5,
    isMultiSelect: false,
    isRequired: false,
    hasTextInput: false,
  },
  {
    id: 11,
    label: 'Do you want to keep the baby?',
    options: {
      'I want to keep the baby': 12,
      'I want to abort the baby': 16,
    },
    ifSkipped: 'submit-chat',
    progress: 62.5,
    isMultiSelect: false,
    isRequired: false,
    hasTextInput: false,
  },
  {
    id: 12,
    label: 'I want to keep the baby but..',
    options: {
      'I can’t afford. I need help with housing/legal/medical support, etc.':
        'submit-chat',
      'I can’t care for the baby because of my poor health': 13,
      'I need to care for my aged parents/special needs children': 14,
      'I have a hectic job/chosen lifestyle': 15,
      'my husband is not supportive': 'submit-chat',
      'I have been told my unborn child has birth defects': 'submit-chat',
    },
    ifSkipped: 'submit-chat',
    progress: 75,
    isMultiSelect: false,
    isRequired: false,
    hasTextInput: false,
  },
  {
    id: 13,
    label: 'You are advised to..',
    options: {
      'Know more about adoption': 'submit-articles',
      'I need help to decide': 'submit-chat',
    },
    ifSkipped: 'submit-chat',
    progress: 87.5,
    isMultiSelect: false,
    isRequired: false,
    hasTextInput: false,
  },
  {
    id: 14,
    label: 'You are advised to..',
    options: {
      'Know more about fostering': 'submit-articles',
      'I need help to decide': 'submit-chat',
    },
    ifSkipped: 'submit-chat',
    progress: 87.5,
    isMultiSelect: false,
    isRequired: false,
    hasTextInput: false,
  },
  {
    id: 15,
    label: 'You are advised to..',
    options: {
      'Know more about childcare support': 'submit-articles',
      'I need help to decide': 'submit-chat',
    },
    ifSkipped: 'submit-chat',
    progress: 87.5,
    isMultiSelect: false,
    isRequired: false,
    hasTextInput: false,
  },
  {
    id: 16,
    label: 'I want to abort baby because..',
    options: {
      'I don’t want children': 17,
      'My family is complete': 17,
      'I have a new job': 17,
    },
    ifSkipped: 'submit-chat',
    progress: 75,
    isMultiSelect: false,
    isRequired: false,
    hasTextInput: false,
  },
  {
    id: 17,
    label: 'Are you sure you want to abort the baby?',
    options: {
      'Know more about abortion': 'submit-articles',
      'I need help to decide': 'submit-chat',
    },
    ifSkipped: 'submit-chat',
    progress: 87.5,
    isMultiSelect: false,
    isRequired: false,
    hasTextInput: false,
  },
  {
    id: 18,
    label: 'Does she want to keep the baby?',
    options: {
      'She wants to keep the baby': 21,
      'She wants to abort the baby': 19,
    },
    ifSkipped: 19,
    progress: 50,
    isMultiSelect: false,
    isRequired: false,
    hasTextInput: false,
  },
  {
    id: 19,
    label: 'She wants to abort the baby because..',
    options: {
      'She doesn’t want children': 20,
      'Her family is complete': 20,
      'She has a new job': 20,
    },
    ifSkipped: 20,
    progress: 75,
    isMultiSelect: false,
    isRequired: false,
    hasTextInput: false,
  },
  {
    id: 20,
    label: 'Is she sure she wants to abort the baby?',
    options: {
      'Know more about abortion': 'submit-articles',
      'She needs help to decide': 'submit-chat',
    },
    ifSkipped: 'submit-chat',
    progress: 75,
    isMultiSelect: false,
    isRequired: false,
    hasTextInput: false,
  },
  {
    id: 21,
    label: 'Options on what to do with the baby',
    options: {
      Parenting: 22,
      Adoption: 25,
      Fostering: 26,
    },
    ifSkipped: 'submit-chat',
    progress: 78,
    isMultiSelect: false,
    isRequired: false,
    hasTextInput: false,
  },
  {
    id: 22,
    label: 'Parenting',
    options: {
      Yes: 23,
      No: 24,
    },
    ifSkipped: 'submit-chat',
    progress: 85,
    isMultiSelect: false,
    isRequired: false,
    hasTextInput: false,
  },
  {
    id: 23,
    label: 'More about Parenting',
    options: {
      'How to prepare for parenthood': 'submit-articles',
      'What to expect during pregnancy, labour, and delivery':
        'submit-articles',
      'What help is available?': 'submit-chat',
    },
    ifSkipped: 'submit-chat',
    progress: 92,
    isMultiSelect: false,
    isRequired: false,
    hasTextInput: false,
  },
  {
    id: 24,
    label: 'Other options',
    options: {
      Fostering: 'submit-articles',
      Adoption: 'submit-articles',
      'I need help to decide': 'submit-chat',
    },
    ifSkipped: 'submit-chat',
    progress: 92,
    isMultiSelect: false,
    isRequired: false,
    hasTextInput: false,
  },
  {
    id: 25,
    label: 'Adoption',
    options: {
      'Know more about adoption': 'submit-articles',
      'I need help to decide': 'submit-chat',
    },
    ifSkipped: 'submit-chat',
    progress: 87.5,
    isMultiSelect: false,
    isRequired: false,
    hasTextInput: false,
  },
  {
    id: 26,
    label: 'Fostering',
    options: {
      'Know more about fostering': 'submit-articles',
      'I need help to decide': 'submit-chat',
    },
    ifSkipped: 'submit-chat',
    progress: 87.5,
    isMultiSelect: false,
    isRequired: false,
    hasTextInput: false,
  },
]

export default questions
export type { Question }
