name: Run BE Tests on Pull Request

env:
  SERVICE_NAME: backend
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

on:
  pull_request:
    branches:
      - main

jobs:
  typecheck-and-lint:
    name: Typecheck and Linting
    runs-on: ubuntu-latest
    environment: prod
    defaults:
      run:
        working-directory: "apps/backend"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: "pnpm-lock.yaml"

      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Typescript Check
        run: npm run ts:check

      - name: Unit Tests
        run: npm run test